### ISSUE TITLE
Aborts half way through with error

### ISSUE THREAD

**Issue by bugmancx** [RhinoRhys/radarr-collections#105]
The script frequently aborts for me while only getting part way through scanning movies.

I get the following error:

Traceback (most recent call last):
  File "/app/rcm.py", line 525, in <module>
    collection_check(col_id)
  File "/app/rcm.py", line 255, in collection_check
    elif not cache: input_id = int(config[u'adding'][u'profile'])
ValueError: invalid literal for int() with base 10: ''
Found 0 Movies

**Comment by bugmancx** [comment]
Note: It does this after having scanned quite a number of movies and then aborts. It does not always abort at the same place.

**Comment by RhinoRhys** [comment]
In the rcm.conf file make sure the line `profile =` has a value set. If you don't want to use people monitoring or single scan mode, it can be set to 0. It does not abort the same place every time because it holds a memory of previous scans but as it has thrown an error and is yet to complete a full scan, you will need to run it with the -f argument in your docker file to override the memory and complete a full scan.

**Comment by bugmancx** [comment]
I already have `profile = ` set in the rcm.conf file and I am using `-f` in the arguments, but the issue is persisting.

I have attached the conf file and the docker-compose.yml that I am using.
[docker-compose.yml.txt](https://github.com/RhinoRhys/radarr-collections/files/3639097/docker-compose.yml.txt)

[rcm.conf.txt](https://github.com/RhinoRhys/radarr-collections/files/3639100/rcm.conf.txt)

**Comment by bugmancx** [comment]
I deleted the memory.dat file and seemed to get a clean run.

**Comment by RhinoRhys** [comment]
Deleting memory.dat is a slightly more hardcore way than using -f to reset everything but if that has worked, brilliant. I'm guessing there must have been a different error the very first time because it doesn't actually execute line 525 on the initial run and since then your issue was an incorrect memory file. It's trying to scan a collection from your database and not finding any of the movies from that collection in it's memory so reverting to the single scan mode template profile which wasn't set (the file you uploaded, the profile variable had no TMDB ID number after the equals sign) and thus throwing this error. Also I've removed your rcm.conf as it had personal details in. Glad it's working now and thanks for your interest in my project.
